PROCESS BEFORE OUTPUT.
*&SPWIZARD: PBO FLOW LOGIC FOR TABLECONTROL 'TC_OUT_SG21'
  MODULE TC_OUT_SG21_CHANGE_TC_ATTR.
*&SPWIZARD: MODULE TC_OUT_SG21_CHANGE_COL_ATTR.
  LOOP AT   LT_OUTBOUND
       INTO LS_OUTBOUND
       WITH CONTROL TC_OUT_SG21
       CURSOR TC_OUT_SG21-CURRENT_LINE.
    MODULE TC_OUT_SG21_GET_LINES.
*&SPWIZARD:   MODULE TC_OUT_SG21_CHANGE_FIELD_ATTR
  ENDLOOP.

 MODULE STATUS_3013.
*
PROCESS AFTER INPUT.
*&SPWIZARD: PAI FLOW LOGIC FOR TABLECONTROL 'TC_OUT_SG21'
  LOOP AT LT_OUTBOUND.
    CHAIN.
      FIELD LS_OUTBOUND-VBELN.
      FIELD LS_OUTBOUND-POSNR.
      FIELD LS_OUTBOUND-MATNR.
      FIELD LS_OUTBOUND-LFIMG.
      FIELD LS_OUTBOUND-VRKME.
      FIELD LS_OUTBOUND-WERKS.
      FIELD LS_OUTBOUND-LGORT.
      FIELD LS_OUTBOUND-CHARG_IP.
      FIELD LS_OUTBOUND-SERNR_IP.
      FIELD LS_OUTBOUND-MATDOC_POSTED.
      FIELD LS_OUTBOUND-MATYEAR_DISP.
      MODULE TC_OUT_SG21_MODIFY ON CHAIN-REQUEST.
    endchain.
  ENDLOOP.
  MODULE TC_OUT_SG21_USER_COMMAND.
*&SPWIZARD: MODULE TC_OUT_SG21_CHANGE_TC_ATTR.
*&SPWIZARD: MODULE TC_OUT_SG21_CHANGE_COL_ATTR.
 MODULE EXIT_3013 AT EXIT-COMMAND.
 MODULE USER_COMMAND_3013.

PROCESS ON VALUE-REQUEST.
  FIELD LS_OUTBOUND-CHARG_IP MODULE f4_ob_sg21_charg.
