PROCESS BEFORE OUTPUT.
*&SPWIZARD: PBO FLOW LOGIC FOR TABLECONTROL 'TC_RESERVATION'
  MODULE TC_RESERVATION_CHANGE_TC_ATTR.
*&SPWIZARD: MODULE TC_RESERVATION_CHANGE_COL_ATTR.
  LOOP AT   GT_RESB
       INTO GS_RESB
       WITH CONTROL TC_RESERVATION
       CURSOR TC_RESERVATION-CURRENT_LINE.
    MODULE TC_RESERVATION_GET_LINES.
*&SPWIZARD:   MODULE TC_RESERVATION_CHANGE_FIELD_ATTR
  ENDLOOP.

  MODULE STATUS_3021.
PROCESS AFTER INPUT.
*&SPWIZARD: PAI FLOW LOGIC FOR TABLECONTROL 'TC_RESERVATION'
  LOOP AT GT_RESB.
    CHAIN.
      FIELD GS_RESB-RSNUM.
      FIELD GS_RESB-RSPOS.
      FIELD GS_RESB-MATNR.
      FIELD GS_RESB-WERKS.
      FIELD GS_RESB-LGORT.
      FIELD GS_RESB-ERFMG.
      FIELD GS_RESB-ERFME.
      FIELD GS_RESB-CHARG.
      FIELD GS_RESB-SERNR.
      FIELD GS_RESB-MATDOC.
      FIELD GS_RESB-MATYEAR_DISP.
      MODULE TC_RESERVATION_MODIFY ON CHAIN-REQUEST.
    endchain.
    FIELD GS_RESB-SEL
      MODULE TC_RESERVATION_MARK ON REQUEST.
  ENDLOOP.
  MODULE TC_RESERVATION_USER_COMMAND.
*&SPWIZARD: MODULE TC_RESERVATION_CHANGE_TC_ATTR.
*&SPWIZARD: MODULE TC_RESERVATION_CHANGE_COL_ATTR.
  MODULE EXIT_3021 AT EXIT-COMMAND.
  MODULE USER_COMMAND_3021.
